/*!
 * JRaiser 2 Javascript Library
 * event-arg - v1.1.0 (2015-06-01T11:19:11+0800)
 * http://jraiser.org/ | Released under MIT license
 */
define("event-driven/1.1.x/event-arg",null,function(t,e,n){"use strict";function i(){return!1}function a(){return!0}var r=t("base/1.1.x/");return r.createClass(function(t,e){var n=this;r.extend(n,e),n.type=t,n.timeStamp=+new Date},{preventDefault:function(){this.isDefaultPrevented=a},stopPropagation:function(){this.isPropagationStopped=a},isDefaultPrevented:i,isPropagationStopped:i})});
/*!
 * JRaiser 2 Javascript Library
 * event-driven - v1.1.0 (2015-09-02T14:42:46+0800)
 * http://jraiser.org/ | Released under MIT license
 */
define("event-driven/1.1.x/",null,function(e,t,n){"use strict";var r=e("base/1.1.x/"),s=e("./event-arg");return r.createClass(function(e){if(this.__eventHandlers={},e)for(var t in e)e.hasOwnProperty(t)&&e[t]&&this.on(t,e[t])},{trigger:function(e,t,n){var r=this.__eventHandlers[e],a=new s(e,t);if(r)for(var i=0;i<r.length;i++)r[i].call(n||this,a);return a},on:function(e,t){var n=this.__eventHandlers;return n[e]=n[e]||[],n[e].push(t),this},off:function(e,t){switch(arguments.length){case 0:this.__eventHandlers={};break;case 1:delete this.__eventHandlers[e];break;case 2:var n=this.__eventHandlers[e];if(n){for(var r=n.length-1;r>=0;r--)n[r]===t&&n.splice(r,1);n.length||delete this.__eventHandlers[e]}}return this}})});
/*!
 * JRaiser 2 Javascript Library
 * dom-event-proxy - v1.0.0 (2015-07-10T15:41:02+0800)
 * http://jraiser.org/ | Released under MIT license
 */
define("widget/1.1.x/dom-event-proxy",null,function(e,n,t){"use strict";function i(e){return"string"==typeof e&&(e=e.trim().split(/\s+/)),e.length?e:void 0}var r=e("base/1.1.x/"),o=e("dom/1.1.x/");return r.createClass(function(){this._init()},{_init:function(){this._elementRecords=[],this._eventRecords=[],this._handlerRecords={}},_createHandler:function(e){var n=this._handlerRecords;switch(typeof e){case"string":if(n[e])return n[e];throw new Error('handler "'+e+'" does not exist');case"function":e={fn:e};break;default:e={id:e.id,fn:e.fn}}if(e.id=e.id||r.randomStr(),n[e.id])throw new Error('handler "'+e+'" already exists');return e.counter=0,n[e.id]=e,e},on:function(e,n,t,r){var c=this._elementRecords,s=this._eventRecords,f=this._createHandler(t);return n=i(n),e.forEach(function(e){var t,i=c.indexOf(e);-1===i&&(i=c.push(e)-1,s[i]={}),t=s[i],e=o(e),n.forEach(function(n){t[n]=t[n]||{},t[n][f.id]||(t[n][f.id]=!0,f.counter++,e.on(n,f.fn,r))})}),this},off:function(e,n,t){var c=this._elementRecords,s=this._eventRecords,f=this._handlerRecords;arguments.length?(n&&(n=i(n)),e.forEach(function(e){var t=c.indexOf(e);-1!==t&&(e=o(e),r.each(s[t],function(i,o){n&&-1===n.indexOf(o)||(r.each(i,function(n,t){var r=f[t];e.off(o,r.fn),delete i[t],--r.counter<=0&&delete f[t]}),r.isEmptyObject(i)&&delete s[t][o])}),r.isEmptyObject(s[t])&&(c.splice(t,1),s.splice(t,1)))})):(c.forEach(function(e,n){e=o(e),r.each(s[n],function(n,t){r.each(n,function(n,i){e.off(t,f[i].fn)})})}),this._init())}})});
/*!
 * JRaiser 2 Javascript Library
 * widget - v1.1.0 (2015-08-05T10:11:55+0800)
 * http://jraiser.org/ | Released under MIT license
 */
define("widget/1.1.x/",["dom/1.1.x/"],function(t,n,i){"use strict";var e=t("base/1.1.x/"),o=t("event-driven/1.1.x/"),r=t("./dom-event-proxy"),s=n.WidgetBase=e.createClass(function(){},{init:function(){var t=this,n=t._options;t.__inited||(t.__eventDriven=new o(n.events),t.__domEventProxy=new r,t._init(n),t.__inited=!0,t._trigger("init"))},_init:function(t){},inited:function(){return!!this.__inited},_onDOMEvent:function(t,n,i,e){var o,r=this;return"string"==typeof i?(o=i,i={}):"string"==typeof i.fn&&(o=i.fn),o?i.fn=function(){r[o].apply(r,arguments)}:i.id&&!i.fn&&(i=i.id),r.__domEventProxy.on(t,n,i,e),r},_offDOMEvent:function(t,n,i){var e=this.__domEventProxy;return e.off.apply(e,arguments),this},on:function(t,n){return this.__eventDriven.on(t,n),this},off:function(t,n){return this.__eventDriven.off(t,n),this},_trigger:function(t,n){return this.__eventDriven.trigger(t,n,this)},destroy:function(){var t=this;if(t.__inited){t._trigger("destroy"),t._destroy(t._options),t._offDOMEvent(),t.off();for(var n in t)t.hasOwnProperty(n)&&"_options"!==n&&delete t[n]}},_destroy:function(t){},options:function(t){var n=this;n.destroy(),e.extend(n._options,t),n._options.disabled||n.init()}});n.create=function(t,n,i){i=i||s,i&&i.defaultOptions&&(n=e.customExtend(n||{},i.defaultOptions,{overwrite:!1}));var o=function(){};o.prototype=i.prototype;var r=e.createClass(function(t){this._options=e.extend({},n,t),this._options.disabled||this.init()},t,o);return r.defaultOptions=n,r}});