/*!
 * JRaiser 2 Javascript Library
 * event-arg - v1.0.0 (2015-04-27T10:34:29+0800)
 * http://jraiser.org/ | Released under MIT license
 */
define("event-driven/1.1.x/event-arg",null,function(t,e,n){"use strict";function i(){return!1}function a(){return!0}var r=t("base/1.1.x/");return r.createClass(function(t,e){var n=this;r.extend(n,e),n.type=t,n.timeStamp=+new Date},{preventDefault:function(){this.isDefaultPrevented=a},stopPropagation:function(){this.isPropagationStopped=a},isDefaultPrevented:i,isPropagationStopped:i})});
/*!
 * JRaiser 2 Javascript Library
 * event-driven - v1.1.0 (2015-04-29T18:04:00+0800)
 * http://jraiser.org/ | Released under MIT license
 */
define("event-driven/1.1.x/",null,function(e,t,n){"use strict";var r=e("base/1.1.x/"),s=e("./event-arg");return r.createClass(function(e){if(this.__eventHandlers={},e)for(var t in e)e.hasOwnProperty(t)&&this.on(t,e[t])},{trigger:function(e,t,n){var r=this.__eventHandlers[e],a=new s(e,t);if(r)for(var i=0;i<r.length;i++)r[i].call(n||this,a);return a},on:function(e,t){var n=this.__eventHandlers;return n[e]=n[e]||[],n[e].push(t),this},off:function(e,t){switch(arguments.length){case 0:this.__eventHandlers={};break;case 1:delete this.__eventHandlers[e];break;case 2:var n=this.__eventHandlers[e];if(n){for(var r=n.length-1;r>=0;r--)n[r]===t&&n.splice(r,1);n.length||delete this.__eventHandlers[e]}}return this}})});
/*!
 * JRaiser 2 Javascript Library
 * widget - v1.1.0 (2015-04-30T12:11:42+0800)
 * http://jraiser.org/ | Released under MIT license
 */
define("widget/1.1.x/",["dom/1.1.x/"],function(t,e,n){"use strict";var i=t("base/1.1.x/"),o=t("event-driven/1.1.x/"),s=t("dom/1.1.x/"),r=e.WidgetBase=i.createClass(function(){},{init:function(){var t=this,e=t._options;t.__inited||(t.__eventDriven=new o(e.events),t.__domEventNamespace=i.randomStr(".widget-"),t.__domEventRecord={elements:[],types:{}},t._init(e),t.__inited=!0,t._trigger("init"))},_init:function(t){},on:function(t,e){return this.__eventDriven.on(t,e),this},off:function(t,e){return this.__eventDriven.off(t,e),this},_trigger:function(t,e){return this.__eventDriven.trigger(t,e,this)},__normalizeDOMEventTypes:function(t){if("string"==typeof t&&(t=t.split(/\s+/)),t.length){var e=this.__domEventNamespace;return t.map(function(t){return t+e})}},_onDOMEvent:function(t,e,n,i){e=this.__normalizeDOMEventTypes(e);var o=this.__domEventRecord.elements,s=this.__domEventRecord.types;t.on(e,n,i).forEach(function(t){var n=o.indexOf(t);-1===n&&(n=o.push(t)-1,s[n]={}),e.forEach(function(t){s[n][t]=!0})})},_offDOMEvent:function(t,e){var n=this.__domEventRecord.elements,o=this.__domEventRecord.types;switch(arguments.length){case 0:n.forEach(function(t,e){s(t).off(Object.keys(o[e]))}),this.__domEventRecord={elements:[],types:{}};break;case 1:t.forEach(function(t){var e=n.indexOf(t);-1!==e&&(s(t).off(Object.keys(o[e])),n.splice(e,1),delete o[e])});break;case 2:e=this.__normalizeDOMEventTypes(e),t.forEach(function(t){var r=n.indexOf(t);-1!==r&&(s(t).off(e),e.forEach(function(t){delete o[r][t]}),i.isEmptyObject(o[r])&&(n.splice(r,1),delete o[r]))})}},destroy:function(){var t=this;if(t.__inited){t._trigger("destroy"),t._destroy(t._options),t._offDOMEvent(),t.off();for(var e in t)t.hasOwnProperty(e)&&"_options"!==e&&delete t[e]}},_destroy:function(t){},options:function(t){var e=this;e.destroy(),i.extend(e._options,t),e._options.disabled||e.init()}});e.create=function(t,e,n){n=n||r,n&&n.defaultOptions&&(e=i.customExtend(e||{},n.defaultOptions,{overwrite:!1}));var o=function(){};o.prototype=n.prototype;var s=i.createClass(function(t){this._options=i.extend({},e,t),this._options.disabled||this.init()},t,o);return s.defaultOptions=e,s}});