/*!
 * JRaiser 2 Javascript Library
 * base@1.1.0 (2016-06-16T15:36:34+0800)
 * http://jraiser.org/ | Released under MIT license
 */
define("base/1.1.x/",null,function(n,t,r){"use strict";function e(n){if(null==n)throw new Error("target cannot be null");for(var t,r,e=0,o=arguments.length;++e<o;)if(r=arguments[e],null!=r)for(t in r)r.hasOwnProperty(t)&&(n[t]=r[t]);return n}function o(n,t){if(null==n)throw new Error("target cannot be null");if(null==t)return n;var r,e,o,u=[];for(r=2;r<arguments.length;r++)switch(o=arguments[r],typeof o){case"object":for(e in o)d.hasOwnProperty(e)&&u.push(d[e](o[e]));break;case"function":u.push(o)}for(e in t){for(o=!0,r=0;r<u.length;r++)if(u[r].call(window,e,t,n)===!1){o=!1;break}o&&(n[e]=t[e])}return n}function u(n){return n===b}function i(n){return"[object Function]"===m.call(n)}function a(n){return"[object Date]"===m.call(n)}function c(n){return"[object Object]"===m.call(n)}function l(n){if(null!=n)for(var t in n)if(n.hasOwnProperty(t))return!1;return!0}function f(n,t){if(null!=n){var r,e=n.length;if(e===b||i(n)){for(r in n)if(n.hasOwnProperty(r)&&!1===t.call(n[r],n[r],r,n))break}else for(r=-1;++r<e&&!1!==t.call(n[r],n[r],r,n););}return n}function s(n){var t;try{t=Array.prototype.slice.call(n)}catch(r){t=[];for(var e=n.length;e;)t[--e]=n[e]}return t}function p(n,t){for(var r=t.length,e=0,o=n.length;r>e;)n[o++]=t[e++];return n.length=o,n}function h(n){var t;return function(){return n&&(t=n.apply(this,arguments),n=null),t}}function y(n){var t="";do t+=Math.random().toString(36).substr(2);while(t.length<10);return t=t.substr(0,10)+("00000"+Math.abs(new Date)).slice(-6),n&&(t=n+t),t}function g(n){try{delete window[n]}catch(t){window[n]=null}}function w(n,t,r,e){var o=r?function(){r.apply(this,e?"function"==typeof e?e.apply(this,arguments):e:arguments),n.apply(this,arguments)}:function(){n.apply(this,arguments)};if(r){var u=function(){};u.prototype=r.prototype,o.prototype=new u,o.prototype.constructor=o}if(t)for(var i in t)t.hasOwnProperty(i)&&(o.prototype[i]=t[i]);return o}var b,d={overwrite:function(n){return function(t,r,e){return n?!0:!(t in e)}},ignoreNull:function(n){return function(t,r){return n?null!=r[t]:!0}},onlyOwnProperty:function(n){return function(t,r){return n?r.hasOwnProperty(t):!0}},whiteList:function(n){return function(t){return-1!==n.indexOf(t)}},blackList:function(n){return function(t){return-1===n.indexOf(t)}}},m=Object.prototype.toString,v=Array.isArray||function(n){return"[object Array]"===m.call(n)};return{extend:e,customExtend:o,isUndefined:u,isFunction:i,isDate:a,isObject:c,isArray:v,isEmptyObject:l,each:f,toArray:s,merge:p,once:h,randomStr:y,deleteGlobalVar:g,createClass:w}});
/*!
 * JRaiser 2 Javascript Library
 * dom-base@1.1.0 (2016-06-16T15:22:24+0800)
 * http://jraiser.org/ | Released under MIT license
 */
define("dom/1.1.x/dom-base",null,function(n,e,t){"use strict";function r(n){return null!=n&&n.nodeType!==i}function o(n){var e=(n.ownerDocument||n).documentElement;return e?"HTML"!==e.nodeName:!1}function u(n){return null!=n&&n==n.window}function l(n,e,t,r,o){if(null!=e&&"object"==typeof e){for(var u in e)e.hasOwnProperty(u)&&l(n,u,e[u],r,o);return n}var c=n.length;if(t!==i){r=r&&"function"==typeof t;for(var f=-1;++f<c;)o.set.call(n,n[f],e,r?t.call(n[f],o.get.call(n,n[f],e),f):t);return n}return c?o.get.call(n,n[0],e):null}var i,c=/\s+/;return{isNode:r,isXMLNode:o,isWindow:u,isHTMLElement:function(n,e){return!u(n)&&r(n)&&!o(n)&&(1===n.nodeType||e&&9===n.nodeType)},getWindow:function(n){return u(n)?n:9===n.nodeType?n.defaultView||n.parentWindow:null},splitBySpace:function(n){return"string"==typeof n&&(n=n.split(c)),null==n||0===n.length?null:n},access:l}});
/*!
 * JRaiser 2 Javascript Library
 * dom-data@1.1.1 (2016-06-16T15:22:35+0800)
 * http://jraiser.org/ | Released under MIT license
 */
define("dom/1.1.x/dom-data",null,function(e,n,t){"use strict";function r(e){var n=new l(e||{});return f.add(n),n}function i(e,n){return h.get(e,n)}function a(e,n,t){h.set(e,n,t)}function o(e,n){null==n?h.clear(e):n.forEach(function(n){h.remove(e,n)})}var c=e("base/1.1.x/"),s=e("./dom-base"),u=function(){function e(e){return s.isWindow(e)||!s.isNode(e)?2:null==e||1!==e.nodeType&&9!==e.nodeType?0:s.isXMLNode(e)||t[e.nodeName]?2:1}function n(e){if(e[r])try{delete e[r]}catch(n){e[r]=null}}var t={OBJECT:!0,EMBED:!0,APPLET:!0},r="_jraiser_nodeid_"+ +new Date+"_",i=0,a={};return{get:function(n,t){var o;switch(e(n)){case 1:o=n[r],o||t||(o=n[r]=new Number(++i));break;case 2:for(var c in a)if(a[c]===n){o=c;break}o||t||(o=++i,a[o]=n)}return o?o.valueOf():void 0},remove:function(t){switch(e(t)){case 1:n(t);break;case 2:for(var r in a)if(a[r]===t){delete a[r];break}}}}}(),f=function(){var e=[];return{add:function(n){return e.push(n)-1},clear:function(n){for(var t=e.length-1;t>=0;t--)e[t].clear(n)},clone:function(n,t){for(var r=e.length-1;r>=0;r--)e[r].clone(n,t)}}}(),l=c.createClass(function(e){this._space={},this._cloneable=e.cloneable!==!1,this._onClone=e.onClone},{_findData:function(e){return this._space[u.get(e,!0)]},keys:function(e){var n=this._findData(e),t=[];if(n)for(var r in n)n.hasOwnProperty(r)&&t.push(r);return t},get:function(e,n){var t=this._findData(e);return t&&t.hasOwnProperty(n)?t[n]:void 0},set:function(e,n,t){var r=u.get(e);if(r){var i=this._space;i[r]||(i[r]={}),i[r][n]=t}},remove:function(e,n){var t=this._findData(e);t&&(delete t[n],c.isEmptyObject(t)&&this.clear(e))},clear:function(e){delete this._space[u.get(e,!0)]},clone:function(e,n){if(this._cloneable){var t=this._findData(n);if(t){var r=u.get(e),i=this._space[r]=this._space[r]||{};for(var a in t)t.hasOwnProperty(a)&&(i[a]=t[a]);this._onClone&&this._onClone(e,n)}}}}),h=r();return{createDataSpace:r,clearAll:function(e){f.clear(e),u.remove(e)},cloneAll:function(e,n){return f.clone(e,n)},removeUniqueId:function(e){u.remove(e)},shortcuts:{data:function(e,n){return s.access(this,e,n,!0,{get:i,set:a})},removeData:function(e){return null!=e&&(e=s.splitBySpace(e)),this.forEach(function(n){o(n,e)}),this}}}});